import { useContext } from 'react';
import SettlementSummary from '../components/settlement/SettlementSummary';
import SettlementTable from '../components/settlement/SettlementTable';
import { AppContext } from '../context/AppContext';
import { formatDateTime } from '../utils/dateUtils';
import useAuth from '../hooks/useAuth';

const SettlementPage = () => {
  const { settlements, setSettlements, tripLocked, setTripLocked, addHistoryEvent } = useContext(AppContext);
  const { user } = useAuth();

  const markPaid = (id) => {
    const paidAt = new Date().toISOString();

    setSettlements((prev) =>
      prev.map((item) => (item.id === id ? { ...item, status: 'PAID', paidAt: item.paidAt || paidAt } : item))
    );
    addHistoryEvent('Settlement Confirmed', `Settlement row #${id} marked paid.`);
  };

  const downloadReceipt = (settlement) => {
    const paidOn = settlement.paidAt ? formatDateTime(settlement.paidAt) : 'Not Available';
    const receiptId = `RCPT-${settlement.id}`;
    const generatedAt = formatDateTime(new Date().toISOString());
    const content = [
      'Team Expense Management System',
      'Debt Settlement Receipt',
      '------------------------------',
      `Receipt ID: ${receiptId}`,
      `Team: ${settlement.teamName || '-'}`,
      `Expense: ${settlement.expenseTitle || `Expense #${settlement.expenseId}`}`,
      `From: ${settlement.from}`,
      `To: ${settlement.to}`,
      `Amount: Rs. ${settlement.amount}`,
      `Status: ${settlement.status}`,
      `Paid On: ${paidOn}`,
      `Generated At: ${generatedAt}`,
      `Generated By: ${user?.name || 'Unknown User'}`
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `settlement-receipt-${settlement.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    addHistoryEvent('Settlement Receipt Downloaded', `Receipt ${receiptId} downloaded for settlement row #${settlement.id}.`);
  };

  const lockTrip = () => {
    setTripLocked(true);
    addHistoryEvent('Trip Locked', 'All balances cleared, modifications are disabled.');
  };

  const pending = settlements.filter((item) => item.status !== 'PAID').length;

  return (
    <div className="stack-gap-lg">
      <div className="page-header">
        <h1>Debt Settlement</h1>
        <button className="btn btn-primary" disabled={tripLocked || pending > 0} onClick={lockTrip}>
          Activate Trip Lock
        </button>
      </div>
      <div className="settlement-layout">
        <SettlementSummary rows={settlements} tripLocked={tripLocked} />
        <SettlementTable
          rows={settlements}
          onMarkPaid={markPaid}
          onDownloadReceipt={downloadReceipt}
          disabled={tripLocked}
        />
      </div>
    </div>
  );
};

export default SettlementPage;
